### ISSUE TITLE
mergesortedarr([38, 27, 43],[3, 9, 82, 10])

### ISSUE THREAD

**Issue by vishalkumar9dec** [theja-m/Data-Structures-and-Algorithms#22]
Hi Theja-m,

I was referring this repo for DS in python. I found one issue with merge-sorted array algorithm that has been implemented.

for the input mergesortedarr([38, 27, 43],[3, 9, 82, 10]) the output comes as [3, 9, 38, 27, 43, 82, 10], which is not correct.

Can you please check and review?

**Comment by joytsay** [comment]
i just found that the original question gives two "already sorted arrays", 
so input [38, 27, 43] and [3, 9, 82, 10] are invalid

if you put [27,38,43] and [3,9,10,82] into the code 
it will output [3, 9, 10, 27, 38, 43, 82] which is correct

**Comment by theja-m** [comment]
Yes, as mentioned by joytsay the problem statement is 'Merge two sorted arrays'. The array input must be sorted.
So  input [38, 27, 43] and [3, 9, 82, 10] are invalid
