### ISSUE TITLE
Array Implementation code reg.,

### ISSUE THREAD

**Issue by gudiausha** [theja-m/Data-Structures-and-Algorithms#5]
Hello @theja-m first of all good work. Came to this repo from ZTM Data Structures. I found an issue in the array implementation.py code. I feel the code is just reinventing the wheel...i.e you are simply defining the lists(which are in-built in python) again. As per my understanding the main difference between a list & array is the latter takes homogeneous elements. This main part itself is missing is this code. Thanks :)

**Comment by farseenmanekhan1232** [comment]
Thank You for this REPO
GBU

**Comment by theja-m** [comment]
You are actually right, we can make use of dictionary to implement an array. I'll change the implementation or if you are interested to change, I will be happy to merge the pull request.

**Comment by gudiausha** [comment]
Hello,
I have implemented it using lists & have it my repo...maybe u can use of
it's ok with you.

Regards,
Pratyusha
